Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,9 +3,6 @@ name: Deploy to Staging & Production
 
 # This workflow is triggered when a branch is merged to the main branch and CI checks have completed
 on:
-  push:
-    branches:
-      - main 
   workflow_run:
     workflows: ["Code scanning", "Code testing & linting"]
     types:
@@ -20,23 +17,35 @@ env:
   BUCKET_NAME: ddt-build-files # Set the name of the root S3 bucket where the build files are stored
 
 jobs:
+  # Check CI workflows are successful
+  ci_status_check:
+    name: 'CI Status Check'
+    runs-on: ubuntu-latest
+    steps:
+      - name: 'Check CI Workflows'
+        id: check-status
+        run: |
+          # Check if the pushed branch is main
+          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
+            # Check if the workflows "Code scanning" and "Code testing & linting" have completed successfully
+            if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
+              echo "The 'Code scanning' and 'Code testing & linting' workflows have completed successfully, and it's a push to main."
+            else
+              echo "Either the 'Code scanning' or 'Code testing & linting' workflows failed, or it's not a push to main."
+              exit 1
+            fi
+          else
+            echo "This is not a push to the main branch. Skipping the deployment."
+            exit 0
+          fi
   # Deploy to staging for UAT and application checks before manual approval for Production
   deploy_staging:
     name: 'Deploy to Staging'
     environment: staging
     runs-on: ubuntu-latest
+    needs: ci_status_check
 
     steps:        
-    # Only run deployment if CI stages are successful
-    - name: 'Check CI Stages are successful'
-      run: |
-          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
-            echo "Code Scanning and Code Testing & Linting were successful."
-          else
-            echo "Code Linting or Code Scanning failed."
-            exit 1
-          fi
-
     - name: 'Checkout repository'
       uses: actions/checkout@v3
 
